# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 004260a586ae8fa21262cdd9dd800ae5249e3e9fea05d7ca8dc7b452536c28c53a5869f02befd8fb7932f45a304a8fd12699e6a9b268c566bff8dabe74c4f05d

test:
  secret_key_base: 72114600f31e5386898fecfb8d93f6231aab8c5a0e3f73f16ee018a7c539c376f9695cc6a514102f3feee95bb8d83b1b58618ed55f6d2629de94e4a6494f5de2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
